#!/usr/bin/env bash
# bootstrap-worktree.sh — make a freshly created git worktree RUNNABLE.
#
# `git worktree add` only checks out tracked files. Everything in .gitignore —
# node_modules, .env files, certs, .vercel link — does NOT come along, so a bare
# worktree won't lint/typecheck/test/run until provisioned. The dispatcher calls
# this after every `git worktree add`; harness-init calls it once on the host
# worktree (which also validates the script).
#
# Contract:  scripts/bootstrap-worktree.sh <target-worktree-path>
#   - Idempotent (safe to re-run; skips installs when the lockfile is unchanged).
#   - Non-interactive (runs unattended inside the loop).
#   - Copies gitignored runtime files SOURCE-CHECKOUT -> WORKTREE only. Never the
#     reverse, never deletes from source. (Harness Invariant 6.)
#
# Generated by /harness-init from a scan of this repo; you own and tune it.

set -uo pipefail

TARGET="${1:?usage: bootstrap-worktree.sh <target-worktree-path>}"
[[ -d "$TARGET" ]] || { echo "bootstrap: target '$TARGET' is not a directory" >&2; exit 1; }
TARGET="$(cd "$TARGET" && pwd)"

# Source checkout = the MAIN worktree (where the real gitignored files live).
# `--git-common-dir` resolves to the shared .git; its parent is the main worktree.
COMMON="$(git -C "$TARGET" rev-parse --git-common-dir 2>/dev/null)" \
  || { echo "bootstrap: '$TARGET' is not inside a git repo" >&2; exit 1; }
SRC="$(cd "$(dirname "$COMMON")" && pwd)"

# SAFETY (Invariant 6): never provision the human's primary checkout. We only ever
# write INTO a *-harness* worktree. If target == source, refuse.
if [[ "$TARGET" == "$SRC" ]]; then
  echo "bootstrap: refusing to run against the source checkout ($SRC)" >&2
  exit 1
fi
echo "bootstrap: source=$SRC"
echo "bootstrap: target=$TARGET"

# ---------------------------------------------------------------------------
# 1. COPY GITIGNORED RUNTIME FILES (secrets/config) SOURCE -> TARGET.
#    Copy only files that exist in source; copy only when missing or different.
#    Never delete, never copy target -> source. Same machine, same user.
# ---------------------------------------------------------------------------
SECRET_FILES=(
  ".env.local"                          # root app env
  ".env.production.local"               # root prod env
  "pk-APKA4NJ63SK4YPQIZU5D.pem"         # signing key
  "rsa-APKA4NJ63SK4YPQIZU5D.pem"        # signing key
  "backend/.env.integration"            # backend integration env
  "backend/samconfig.toml"              # backend SAM deploy config
  "frontend/.env.local"                 # frontend local env
  "frontend/.env.preview"               # frontend preview env
  "frontend/.env.prod"                  # frontend prod env
  "e2e/.env"                            # e2e env
)

copy_file() {  # $1 = relative path
  local rel="$1" s="$SRC/$1" d="$TARGET/$1"
  [[ -e "$s" ]] || return 0                      # optional file absent in source -> skip silently
  if [[ -e "$d" ]] && cmp -s "$s" "$d"; then return 0; fi   # already present & identical -> no-op
  mkdir -p "$(dirname "$d")"
  cp -p "$s" "$d" && echo "  copied  $rel"
}

echo "bootstrap: copying gitignored runtime files…"
for rel in "${SECRET_FILES[@]}"; do copy_file "$rel"; done

# .vercel/ is a directory (project link) — copy recursively, source -> target only.
if [[ -d "$SRC/.vercel" ]]; then
  mkdir -p "$TARGET/.vercel"
  cp -pr "$SRC/.vercel/." "$TARGET/.vercel/" && echo "  copied  .vercel/"
fi

# ---------------------------------------------------------------------------
# 2. INSTALL DEPENDENCIES per workspace (pnpm monorepo, no root manifest).
#    --frozen-lockfile = reproducible, non-interactive. Idempotent: skip when
#    node_modules exists AND the lockfile hash is unchanged since last install.
#    The stamp lives INSIDE node_modules so the dispatcher's `git clean -fd`
#    (which preserves gitignored node_modules) doesn't wipe it each tick.
# ---------------------------------------------------------------------------
install_ws() {  # $1 = workspace dir
  local ws="$1" dir="$TARGET/$1"
  [[ -f "$dir/package.json" ]] || return 0
  local lock="$dir/pnpm-lock.yaml"
  local stamp="$dir/node_modules/.bootstrap-lock-sha"
  local cur="" ; [[ -f "$lock" ]] && cur="$(sha1sum "$lock" | cut -d' ' -f1)"
  if [[ -d "$dir/node_modules" && -f "$stamp" && "$(cat "$stamp" 2>/dev/null)" == "$cur" ]]; then
    echo "  install ($ws): up-to-date, skipping"
    return 0
  fi
  echo "  install ($ws): pnpm install --frozen-lockfile"
  ( cd "$dir" && pnpm install --frozen-lockfile ) || {
    echo "bootstrap: pnpm install failed in $ws" >&2; return 1; }
  [[ -n "$cur" ]] && printf '%s' "$cur" > "$stamp"
}

echo "bootstrap: installing dependencies…"
rc=0
for ws in backend frontend e2e; do install_ws "$ws" || rc=1; done

# NOTE: the heavier backend build steps (email/ + video-encoder/ sub-installs,
# `tsc` build, `sam build`) are DEPLOYMENT-time and intentionally NOT run here —
# they're slow and not needed for lint / typecheck / fast unit tests. If a feature's
# run-prd-test.sh needs a built backend, add that step here (it runs in the loop).

if (( rc != 0 )); then
  echo "bootstrap: FAILED (see errors above)" >&2
  exit 1
fi
echo "bootstrap: OK — $TARGET is provisioned."
