#!/usr/bin/env bash
# local-checks.sh — the project's DETERMINISTIC GATE.
#
# The harness dispatcher runs this after /implement-mainspec and BEFORE opening a
# PR (two-strike retry: `local-checks.sh fix` -> /fix-local-checks -> STUCK). It is
# the cheapest place to catch correctness problems — left of the reviewer and CI.
# This repo has no git hooks and no CI yet, so this gate carries that weight.
#
# Contract:
#   ./scripts/local-checks.sh        = CHECK   (exit 0 = pass, non-zero = fail)
#   ./scripts/local-checks.sh fix    = AUTOFIX the auto-fixable subset (eslint --fix)
#
# It proves CORRECTNESS, not coverage: correctness/structural checks BLOCK;
# legibility/observability would only WARN. Generated by /harness-init; you own and
# tune it. See .claude/skills/harness-init/references/local-checks-design.md.

set -uo pipefail   # NOT -e: run every check, then aggregate, so one red doesn't mask others.
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

WORKSPACES=(backend frontend e2e)   # pnpm monorepo, no root manifest
TEST_WORKSPACES=(backend frontend)  # fast jest unit suites; e2e is Playwright -> CI, not here

fail=0
section() { printf '\n=== %s ===\n' "$*"; }
red()     { echo "❌ $*" >&2; fail=1; }

# ---------------------------------------------------------------------------
# FIX MODE — autofix only the safe, semantics-preserving subset (eslint --fix).
# The dispatcher's attempt-0 runs this before any agent spends a token.
# ---------------------------------------------------------------------------
if [[ "${1:-check}" == "fix" ]]; then
  for ws in "${WORKSPACES[@]}"; do
    [[ -d "$ws" ]] || continue
    section "eslint --fix ($ws)"
    ( cd "$ws" && pnpm run lint -- --fix ) || echo "  (eslint --fix reported issues in $ws; non-fatal in fix mode)"
  done
  echo
  echo "fix: done (review the working tree; re-run ./scripts/local-checks.sh to verify)."
  exit 0
fi

# ---------------------------------------------------------------------------
# 1. LINT (block) — eslint per workspace.
# ---------------------------------------------------------------------------
for ws in "${WORKSPACES[@]}"; do
  [[ -d "$ws" ]] || continue
  section "lint ($ws)"
  ( cd "$ws" && pnpm run lint ) || red "lint failed in $ws — fix the eslint errors (try ./scripts/local-checks.sh fix for the auto-fixable ones)."
done

# ---------------------------------------------------------------------------
# 2. TYPECHECK (block) — a type error is a correctness failure.
# ---------------------------------------------------------------------------
for ws in "${WORKSPACES[@]}"; do
  [[ -d "$ws" ]] || continue
  section "typecheck ($ws)"
  ( cd "$ws" && pnpm run typecheck ) || red "typecheck failed in $ws — fix the type error; do not @ts-ignore it."
done

# ---------------------------------------------------------------------------
# 3. FAST UNIT TESTS (block) — the shifted-left copy of CI's unit run. Its unique
#    value is catching CROSS-SLICE regressions (slice signals only run per-slice).
#    Fast unit suites only; integration/e2e stays in CI.
# ---------------------------------------------------------------------------
for ws in "${TEST_WORKSPACES[@]}"; do
  [[ -d "$ws" ]] || continue
  section "unit tests ($ws)"
  ( cd "$ws" && pnpm run test:unit ) || red "unit tests failed in $ws — fix the cause; never add .skip/.only to make them pass."
done

# ---------------------------------------------------------------------------
# 4. SKIP-DETECTION (block) — "all tests pass" is gameable: a skipped test is green.
#    Fail if THIS branch's diff ADDS a test-skip/focus marker. A legitimate skip is
#    the human's call at STUCK, never an agent's. (See local-checks-design.md.)
# ---------------------------------------------------------------------------
section "skip-detection"
if git rev-parse --verify --quiet origin/main >/dev/null; then
  base="$(git merge-base origin/main HEAD 2>/dev/null || echo origin/main)"
  added_skips="$(git diff --unified=0 "$base"...HEAD -- \
                   ':(glob)**/*.test.*' ':(glob)**/*.spec.*' ':(glob)**/__tests__/**' 2>/dev/null \
                 | grep -E '^\+' | grep -vE '^\+\+\+' \
                 | grep -nE '\.(skip|only)\b|\b(xit|xdescribe|fit|fdescribe)\b' || true)"
  if [[ -n "$added_skips" ]]; then
    red "this branch ADDS test-skip/focus markers — not allowed for an agent:"
    echo "$added_skips" | sed 's/^/   /' >&2
    echo "   WHY: a skipped/focused test is green but unverified; it games the test gate." >&2
    echo "   FIX: fix the underlying test/code. A legitimate skip is a HUMAN decision at STUCK." >&2
  else
    echo "skip-detection: OK (no added skip/focus markers)"
  fi
else
  echo "skip-detection: SKIPPED (origin/main not available)"
fi

# ---------------------------------------------------------------------------
# 5. CUSTOM INVARIANT LINTS — everything in scripts/lints/ (block). /learn grows
#    this directory over time; running the whole dir means new lints need no rewiring.
# ---------------------------------------------------------------------------
if compgen -G "scripts/lints/*.sh" > /dev/null; then
  for lint in scripts/lints/*.sh; do
    section "lint: $(basename "$lint")"
    [[ -x "$lint" ]] || chmod +x "$lint"
    "$lint" || red "custom lint failed: $lint (read its message above for the fix)."
  done
fi

# ---------------------------------------------------------------------------
# 6. AGENTS.md FRESHNESS — the memory map must not rot (over line cap, stale
#    pointers). Run as WARN-ONLY (non-blocking) for now, for two reasons:
#      (a) Bootstrap window: the Expert (.claude/skills/expert/) is born from the
#          FIRST /learn, after the first merge — but AGENTS.md points to it from
#          day one, so its pointer reads as "missing" until then.
#      (b) The canonical lint's path-existence check also flags slash-command
#          tokens (`/intent`, `/learn`, …) and <f>-scoped filenames in the
#          canonical skill-chain table as if they were repo paths — false
#          positives we don't want to BLOCK on (and the table is kept verbatim).
#    The valuable line-cap signal still surfaces here; promote this to a blocking
#    check once /learn has curated AGENTS.md and the false positives are resolved.
# ---------------------------------------------------------------------------
FRESHNESS=".claude/skills/learn/scripts/check-agents-md.sh"
if [[ -x "$FRESHNESS" ]]; then
  section "AGENTS.md freshness (advisory)"
  "$FRESHNESS" || echo "⚠️  AGENTS.md freshness warnings above (advisory, non-blocking — see local-checks.sh §6)."
fi

echo
if (( fail )); then
  echo "local-checks: FAIL" >&2
  exit 1
fi
echo "local-checks: OK"
